---

- hosts: localhost
  connection: local
  gather_facts: False
tasks:
   - name: Get instances facts
      ec2_instance_facts:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        region: "{{ region }}"
      register: result
   - name: Retrieve all tags from EC2 instance
      ec2_tag:
         region: "{{ ansible_ec2_placement_region }}"
        resource: "{{ ansible_ec2_instance_id }}"
        state: list
      register: ec2_tags  
